name: inception_bonus

networks:
  my_net:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb_data

  wp-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp_data

  owncast-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/owncast_data

services:
  sftp-server:
    build:
      context: ./sftp-server
      args:
        - FTP_USER=${FTP_USER}
        - FTP_USER_PASS=${FTP_USER_PASS}
    container_name: sftp-server
    depends_on:
      wordpress:
        condition: service_healthy
    restart: on-failure
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - my_net
    ports:
      - 22:22

  owncast:
    build: ./owncast
    container_name: owncast
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - owncast-data:/owncast/data

  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: on-failure
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - WP_ADMIN=${WP_ADMIN}
      - WP_USER=${WP_USER}
    networks:
      - my_net
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build:
      context: ./wordpress
      args:
        - WORDPRESS_USER=wordpress_user
    container_name: wordpress
    restart: on-failure
    volumes:
      - wp-files:/var/www/wordpress
    env_file:
      - ./.env
    environment:
      - WP_ADMIN=${WP_ADMIN}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - my_net
    healthcheck:
      test: ["CMD-SHELL", "cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    build:
      context: ./adminer
      args:
        - WORDPRESS_USER=wordpress_user
    container_name: adminer
    restart: on-failure
    volumes:
      - wp-files:/var/www/wordpress
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - my_net

  nginx:
    build: ./nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - wp-files:/var/www/wordpress
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - my_net

  redis:
    build: ./redis
    container_name: redis
    restart: on-failure
    networks:
      - my_net

  static-page:
    build: ./static-page
    container_name: static-page
    restart: on-failure
    ports:
      - 8081:80
    networks:
      - my_net

