name: inception

networks:
  my_network:
    driver: bridge

secrets:
  db_admin_user:
    file: ./srcs/.env
  db_admin_pass:
    file: ./srcs/.env
  db_user:
    file: ./srcs/.env
  db_user_pass:
    file: ./srcs/.env

services:
  mariadb:
    build: ./mandatory/mariadb
    container_name: mariadb:mine
    restart: always
    secrets:
      - db_admin_user

  wordpress:
    build: ./mandatory/wordpress
    # restart: always
    container_name: wordpress:mine
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./srcs/mandatory/wordpress/wp-files:/var/www/wordpress

  nginx:
    image: debian:latest
    build: ./mandatory/nginx
    container_name: nginx:mine
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy

volumes:
  wordpress-db:
    driver: local
    driver_opts:
      type: "nfs"
      o: "rw"
      device: /goinfre/wordpress-db
