name: inception

networks:
  my_network:
    driver: bridge

volumes:
  mariadb-data:

  wp-files:

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: always
    env_file:
      - ./.env
    environment:
      - WP_ADMIN=${WP_ADMIN}
      - WP_USER=${WP_USER}

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wp-files:/var/www/wordpress
    env_file:
      - ./.env
    environment:
      - WP_ADMIN=${WP_ADMIN}
    depends_on:
      mariadb:
        condition: service_started

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:8080
    depends_on:
      wordpress:
        condition: service_started
