name: inception

networks:
  my_net:
    driver: bridge

volumes:
  mariadb-data:

  wp-files:

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    volumes:
      - mariadb-data:/mariadb-data
    restart: always
    env_file:
      - ./.env
    environment:
      - WP_ADMIN=${WP_ADMIN}
      - WP_USER=${WP_USER}
    networks:
      - my_net
    healthcheck:
      start_period: 1m
      interval: 1m
      test:
        [
          "CMD-SHELL",
          '[ -d /mariadb-data ] && [ "$(ls -A /mariadb-data 2>/dev/null)" ]',
        ]

  wordpress:
    build:
      context: ./wordpress
      args:
        - WORDPRESS_USER=wordpress_user
    container_name: wordpress
    restart: always
    volumes:
      - wp-files:/var/www/wordpress
    env_file:
      - ./.env
    environment:
      - WP_ADMIN=${WP_ADMIN}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - my_net
    healthcheck:
      start_period: 1m
      interval: 1m
      test:
        [
          "CMD-SHELL",
          '[ -d /var/www/wordpress ] && [ "$(ls -A /var/www/wordpress 2>/dev/null)" ]',
        ]

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:443
    volumes:
      - wp-files:/var/www/wordpress
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - my_net
