FROM alpine:latest

RUN apk update

RUN apk add \
	php php-fpm \
	php-mysqli php-json php-session php-mbstring php-xml php-xmlwriter php-simplexml \
	php-curl php-gd php-zip php-opcache php-phar php-iconv php-tokenizer php-pdo \
	curl tar

	